stages: 
  - build
  - docker

maven-build:
  image: maven:3-openjdk-17
  stage: build
  script: "mvn package -B -DskipTests"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  image: docker:latest
  script:
  - docker build -t registry.dev.juniorisep.com/bureau-des-legendes/api:test .
