spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

server:
  port:
    8000