spring:
  application:
    name: api
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/devbdl}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  # jpa:
  #   hibernate:
  #     ddl-auto: create

server:
  port:
    8000