spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/bureaudeslegendes
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port:
    8000